from predict import (
    load_model_data,
    normalize_symptom,
    predict_disease
)

from recommend import get_recommendations


# ============================================================
# CONFIGURATION
# ============================================================

MIN_SYMPTOMS_WARNING = 2
LOW_CONFIDENCE_THRESHOLD = 50.0


# ============================================================
# DISPLAY LIST
# ============================================================

def display_list(items):

    if not items:
        print("Information not available.")
        return

    for item in items:
        print(f"• {item}")


# ============================================================
# DISPLAY RECOMMENDATIONS
# ============================================================

def display_recommendations(recommendations):

    print("\n" + "=" * 70)
    print("                 AI HEALTHMATE")
    print("=" * 70)

    print(
        f"\nPredicted Disease: "
        f"{recommendations['disease']}"
    )

    # --------------------------------------------------------
    # DESCRIPTION
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("DESCRIPTION")
    print("-" * 70)

    print(
        recommendations["description"]
    )

    # --------------------------------------------------------
    # MEDICATIONS
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("MEDICATION INFORMATION")
    print("-" * 70)

    display_list(
        recommendations["medications"]
    )

    # --------------------------------------------------------
    # PRECAUTIONS
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("PRECAUTIONS")
    print("-" * 70)

    precautions = recommendations["precautions"]

    if precautions:

        for index, precaution in enumerate(
            precautions,
            start=1
        ):
            print(
                f"{index}. {precaution}"
            )

    else:

        print("Information not available.")

    # --------------------------------------------------------
    # DIET
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("DIET")
    print("-" * 70)

    display_list(
        recommendations["diet"]
    )

    # --------------------------------------------------------
    # WORKOUT
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("WORKOUT")
    print("-" * 70)

    display_list(
        recommendations["workout"]
    )

    # --------------------------------------------------------
    # DISCLAIMER
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("IMPORTANT DISCLAIMER")
    print("=" * 70)

    print(
        "AI HealthMate is an educational and decision-support system."
    )

    print(
        "The prediction is generated by a machine-learning model "
        "and is not a medical diagnosis."
    )

    print(
        "The model score is not a clinical probability or certainty."
    )

    print(
        "Medication information is not a prescription."
    )

    print(
        "Please consult a qualified healthcare professional "
        "for medical advice."
    )

    print("=" * 70)


# ============================================================
# MAIN PROGRAM
# ============================================================

def main():

    print("=" * 70)
    print("                 AI HEALTHMATE")
    print("          AI Disease Prediction System")
    print("=" * 70)

    # ========================================================
    # LOAD MODEL
    # ========================================================

    try:

        model, symptoms, label_mapping = (
            load_model_data()
        )

    except Exception as error:

        print(
            "\nUnable to load the AI HealthMate model."
        )

        print(
            f"Error: {error}"
        )

        return

    # ========================================================
    # DISPLAY AVAILABLE SYMPTOMS
    # ========================================================

    print("\nAvailable symptoms:")
    print("-" * 70)

    for index, symptom in enumerate(
        symptoms,
        start=1
    ):

        print(
            f"{index:3}. {symptom}"
        )

    # ========================================================
    # GET USER INPUT
    # ========================================================

    print("\n" + "-" * 70)
    print("Enter your symptoms separated by commas.")
    print("Example: fever, headache, vomiting")
    print("-" * 70)

    user_input = input(
        "\nEnter symptoms: "
    ).strip()

    # ========================================================
    # EMPTY INPUT VALIDATION
    # ========================================================

    if not user_input:

        print("\nNo symptoms entered.")

        print(
            "Please enter at least one symptom."
        )

        return

    # ========================================================
    # SPLIT INPUT
    # ========================================================

    entered_symptoms = [
        symptom.strip()
        for symptom in user_input.split(",")
        if symptom.strip()
    ]

    # ========================================================
    # MATCH SYMPTOMS
    # ========================================================

    recognized_symptoms = []
    unrecognized_symptoms = []

    for symptom in entered_symptoms:

        normalized = normalize_symptom(
            symptom,
            symptoms
        )

        if normalized:

            if normalized not in recognized_symptoms:

                recognized_symptoms.append(
                    normalized
                )

        else:

            unrecognized_symptoms.append(
                symptom
            )

    # ========================================================
    # DISPLAY SYMPTOM ANALYSIS
    # ========================================================

    print("\n" + "-" * 70)
    print("SYMPTOM ANALYSIS")
    print("-" * 70)

    print("\nRecognized symptoms:")

    if recognized_symptoms:

        for symptom in recognized_symptoms:

            print(
                f"✓ {symptom}"
            )

    else:

        print("None")

    # ========================================================
    # DISPLAY UNRECOGNIZED SYMPTOMS
    # ========================================================

    if unrecognized_symptoms:

        print("\nUnrecognized symptoms:")

        for symptom in unrecognized_symptoms:

            print(
                f"✗ {symptom}"
            )

    # ========================================================
    # NO VALID SYMPTOMS
    # ========================================================

    if not recognized_symptoms:

        print(
            "\nNo valid symptoms were recognized."
        )

        print(
            "Please use symptoms from the available list."
        )

        return

    # ========================================================
    # TOO FEW SYMPTOMS WARNING
    # ========================================================

    if len(recognized_symptoms) < MIN_SYMPTOMS_WARNING:

        print("\nWARNING:")

        print(
            "Only one symptom was recognized."
        )

        print(
            "Predictions based on very few symptoms may "
            "be unreliable."
        )

    # ========================================================
    # PREDICTION
    # ========================================================

    print(
        "\nPredicting disease..."
    )

    try:

        (
            predicted_disease,
            confidence,
            top_predictions
        ) = predict_disease(
            model,
            symptoms,
            label_mapping,
            recognized_symptoms
        )

    except Exception as error:

        print(
            "\nPrediction failed."
        )

        print(
            f"Error: {error}"
        )

        return

    # ========================================================
    # DISPLAY PREDICTION
    # ========================================================

    print("\n" + "=" * 70)
    print("PREDICTION RESULT")
    print("=" * 70)

    print(
        f"\nPredicted Disease: "
        f"{predicted_disease}"
    )

    print(
        f"Model score: "
        f"{confidence:.2f}%"
    )

    # ========================================================
    # LOW SCORE WARNING
    # ========================================================

    if confidence < LOW_CONFIDENCE_THRESHOLD:

        print("\nWARNING:")

        print(
            "The model score is relatively low."
        )

        print(
            "The prediction should not be treated as reliable "
            "without professional medical evaluation."
        )

    # ========================================================
    # TOP 3 PREDICTIONS
    # ========================================================

    print("\nTop 3 Model Predictions:")

    for rank, (
        disease,
        score
    ) in enumerate(
        top_predictions,
        start=1
    ):

        print(
            f"{rank}. {disease} "
            f"- Model score: {score:.2f}%"
        )

    # ========================================================
    # SELECTED SYMPTOMS
    # ========================================================

    print("\nSelected symptoms:")

    for symptom in recognized_symptoms:

        print(
            f"- {symptom}"
        )

    # ========================================================
    # GET RECOMMENDATIONS
    # ========================================================

    try:

        recommendations = get_recommendations(
            predicted_disease
        )

    except Exception as error:

        print(
            "\nUnable to retrieve recommendation information."
        )

        print(
            f"Error: {error}"
        )

        return

    # ========================================================
    # CHECK RECOMMENDATIONS
    # ========================================================

    if not recommendations:

        print(
            "\nRecommendation information was not found."
        )

        return

    # ========================================================
    # DISPLAY COMPLETE RESULT
    # ========================================================

    display_recommendations(
        recommendations
    )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()