from predict import (
    load_model_data,
    normalize_symptom,
    predict_disease
)

from recommend import get_recommendations


# ============================================================
# DISPLAY RECOMMENDATIONS
# ============================================================

def display_recommendations(recommendations):

    print("\n" + "=" * 70)
    print("                 AI HEALTHMATE")
    print("=" * 70)

    # --------------------------------------------------------
    # PREDICTED DISEASE
    # --------------------------------------------------------

    print(
        f"\nPredicted Disease: "
        f"{recommendations['disease']}"
    )


    # --------------------------------------------------------
    # DESCRIPTION
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("DESCRIPTION")
    print("-" * 70)

    print(
        recommendations["description"]
    )


    # --------------------------------------------------------
    # MEDICATIONS
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("MEDICATION INFORMATION")
    print("-" * 70)

    medications = recommendations["medications"]

    if medications:

        for medication in medications:
            print(f"• {medication}")

    else:

        print("Information not available.")


    # --------------------------------------------------------
    # PRECAUTIONS
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("PRECAUTIONS")
    print("-" * 70)

    precautions = recommendations["precautions"]

    if precautions:

        for index, precaution in enumerate(
            precautions,
            start=1
        ):

            print(
                f"{index}. {precaution}"
            )

    else:

        print("Information not available.")


    # --------------------------------------------------------
    # DIET
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("DIET")
    print("-" * 70)

    diet = recommendations["diet"]

    if diet:

        for item in diet:
            print(f"• {item}")

    else:

        print("Information not available.")


    # --------------------------------------------------------
    # WORKOUT
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("WORKOUT")
    print("-" * 70)

    workout = recommendations["workout"]

    if workout:

        for item in workout:
            print(f"• {item}")

    else:

        print("Information not available.")


    # --------------------------------------------------------
    # DISCLAIMER
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("IMPORTANT DISCLAIMER")
    print("=" * 70)

    print(
        "AI HealthMate is an educational and decision-support system."
    )

    print(
        "The prediction is generated by a machine-learning model and is"
    )

    print(
        "not a medical diagnosis. Medication information is not a prescription."
    )

    print(
        "Please consult a qualified healthcare professional for medical advice."
    )

    print("=" * 70)


# ============================================================
# MAIN PROGRAM
# ============================================================

def main():

    print("=" * 70)
    print("                 AI HEALTHMATE")
    print("          AI Disease Prediction System")
    print("=" * 70)


    # ========================================================
    # LOAD MODEL
    # ========================================================

    model, symptoms, label_mapping = load_model_data()


    # ========================================================
    # DISPLAY AVAILABLE SYMPTOMS
    # ========================================================

    print("\nAvailable symptoms:")
    print("-" * 70)

    for index, symptom in enumerate(
        symptoms,
        start=1
    ):

        print(
            f"{index:3}. {symptom}"
        )


    # ========================================================
    # GET USER INPUT
    # ========================================================

    print("\n" + "-" * 70)
    print("Enter your symptoms separated by commas.")
    print("Example: fever, headache, vomiting")
    print("-" * 70)

    user_input = input(
        "\nEnter symptoms: "
    ).strip()


    # ========================================================
    # CHECK EMPTY INPUT
    # ========================================================

    if not user_input:

        print("\nNo symptoms entered.")

        return


    # ========================================================
    # SPLIT USER SYMPTOMS
    # ========================================================

    entered_symptoms = [
        symptom.strip()
        for symptom in user_input.split(",")
        if symptom.strip()
    ]


    # ========================================================
    # MATCH SYMPTOMS
    # ========================================================

    recognized_symptoms = []
    unrecognized_symptoms = []


    for symptom in entered_symptoms:

        normalized = normalize_symptom(
            symptom,
            symptoms
        )


        if normalized:

            if normalized not in recognized_symptoms:

                recognized_symptoms.append(
                    normalized
                )

        else:

            unrecognized_symptoms.append(
                symptom
            )


    # ========================================================
    # DISPLAY SYMPTOM ANALYSIS
    # ========================================================

    print("\n" + "-" * 70)
    print("SYMPTOM ANALYSIS")
    print("-" * 70)


    print("\nRecognized symptoms:")

    if recognized_symptoms:

        for symptom in recognized_symptoms:

            print(
                f"✓ {symptom}"
            )

    else:

        print("None")


    # --------------------------------------------------------
    # UNRECOGNIZED SYMPTOMS
    # --------------------------------------------------------

    if unrecognized_symptoms:

        print("\nUnrecognized symptoms:")

        for symptom in unrecognized_symptoms:

            print(
                f"✗ {symptom}"
            )


    # ========================================================
    # REQUIRE VALID SYMPTOM
    # ========================================================

    if not recognized_symptoms:

        print(
            "\nNo valid symptoms were recognized."
        )

        print(
            "Please enter symptoms using the available symptom names."
        )

        return


    # ========================================================
    # PREDICT DISEASE
    # ========================================================

    print(
        "\nPredicting disease..."
    )


    predicted_disease, confidence, top_predictions = predict_disease(
        model,
        symptoms,
        label_mapping,
        recognized_symptoms
    )


    # ========================================================
    # DISPLAY PREDICTION
    # ========================================================

    print("\n" + "=" * 70)
    print("PREDICTION RESULT")
    print("=" * 70)


    print(
        f"\nPredicted Disease: "
        f"{predicted_disease}"
    )


    print(
        f"Model confidence score: "
        f"{confidence:.2f}%"
    )


    # ========================================================
    # TOP 3 PREDICTIONS
    # ========================================================

    print("\nTop 3 Model Predictions:")


    for rank, (
        disease,
        score
    ) in enumerate(
        top_predictions,
        start=1
    ):

        print(
            f"{rank}. {disease} "
            f"- Model score: {score:.2f}%"
        )


    # ========================================================
    # SELECTED SYMPTOMS
    # ========================================================

    print("\nSelected symptoms:")

    for symptom in recognized_symptoms:

        print(
            f"- {symptom}"
        )


    # ========================================================
    # GET RECOMMENDATIONS
    # ========================================================

    recommendations = get_recommendations(
        predicted_disease
    )


    # ========================================================
    # CHECK RECOMMENDATIONS
    # ========================================================

    if recommendations is None:

        print(
            "\nRecommendation information "
            "not found for this disease."
        )

        return


    # ========================================================
    # DISPLAY COMPLETE RESULT
    # ========================================================

    display_recommendations(
        recommendations
    )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()